# Jamels CircleCI configuration file
version: 2.1

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
      - deploy:
          filters:
            branches:
              only:
                - main
          requires:
            - build

jobs:
  build:
    working_directory: ~/SimpleApplication
    docker:
        - image: circleci/node:23.10.0
    steps:
      - checkout
      - run:
          name: update-npm
          command: npm install -g npm@latest
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: install-npm-packages
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
  deploy:
    docker:
        - image: circleci/node:23.10.0
    steps:
      - run:
          name: deploy-application
          command: ssh -o StrictHostKeyChecking=no $EC2_USERNAME@$EC2_PUBLIC_DNS "
            rm -rf DevOpsCA/;git clone https://github.com/JamelAB/DevOpsCA.git; source
             DevOpsCA/deploy.sh"